working_dir: ./
excludes: ["/.git/", "**/*log*", "log_*", "*.log", "*.jsonl", "*.parquet", "*.json", "*.whl"]
env_vars:
  TORCH_NCCL_AVOID_RECORD_STREAMS: "1"
  VLLM_USE_V1: "1"
  VLLM_WORKER_MULTIPROC_METHOD: "spawn"
  HYDRA_FULL_ERROR: "1"
